
var car1Data = {
  "camera1":{
    'roadName':'保福寺桥西',
    "carList":[
      {
        id:"123",
        time:"",
        isDanger:false,
        dangerReason:"无",
        car:{
          brand:"奥迪",
          number:"376211",
          color:"黑色",
          pic:"images/car.png",
        }
      },
      {
        id:"1234",
        time:"",
        isDanger: true,
        dangerReason:"犯罪违法",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      }
    ]
  },
  "camera2":{
    "roadName": "成府路口南",
    "carList":[
      {
        id:"123459",
        time:"",
        isDanger: false,
        dangerReason:"无",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123458",
        time:"",
        isDanger: false,
        dangerReason:"无",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123457",
        time:"",
        isDanger: true,
        dangerReason:"犯罪违法",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123456",
        time:"",
        isDanger: false,
        dangerReason:"无",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123455",
        time:"",
        isDanger: true,
        dangerReason:"犯罪违法",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123454",
        time:"",
        isDanger: true,
        dangerReason:"犯罪违法",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123453",
        time:"",
        isDanger: true,
        dangerReason:"犯罪违法",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123452",
        time:"",
        isDanger: false,
        dangerReason:"无",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123451",
        time:"",
        isDanger: true,
        dangerReason:"犯罪违法",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123450",
        time:"",
        isDanger: false,
        dangerReason:"无",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
      {
        id:"123450",
        time:"",
        isDanger: false,
        dangerReason:"无",
        car:{
          brand:"标致",
          number:"88777",
          color:"红色",
          pic:"images/car.png",
        }
      },
    ]
  }
}

